M48
; DRILL file {KiCad 8.0.8} date 2025-06-01T20:52:01+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-01T20:52:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.985Y-4.39
T2
X3.42Y-1.75
X3.42Y-5.13
X3.675Y-3.4452
X4.125Y-3.4452
X6.8Y-1.75
X6.8Y-5.13
M30
